name: Bug report
description: Report incorrect behavior
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Share minimal code or steps to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 22.0.0
